import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { getLocale, getTranslations } from 'next-intl/server';

import { LandingHero } from '@/components/landing/landing-hero';
import { LandingFeatures } from '@/components/landing/landing-features';
import { LandingInstall } from '@/components/landing/landing-install';
import { LandingRedirect } from '@/components/landing/landing-redirect';
import { LandingTrust } from '@/components/landing/landing-trust';
import { getRequestOrigin } from '@/lib/request-origin';
import { fetchSignupMode } from '@/lib/signup-mode';

/** 1200×630 share card, generated by `npm run og` (scripts/generate-og.mjs). */
const OG_IMAGE_PATH = '/og/miaurmario-og.png';

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations('landing');
  const locale = await getLocale();
  // Absolute URLs: WhatsApp and friends will not resolve a relative og:image.
  const origin = getRequestOrigin(headers());
  const title = t('metaTitle');
  const description = t('metaDescription');
  const image = {
    url: `${origin}${OG_IMAGE_PATH}`,
    width: 1200,
    height: 630,
    alt: t('ogImageAlt'),
    type: 'image/png',
  };

  return {
    metadataBase: new URL(origin),
    title,
    description,
    alternates: { canonical: '/' },
    openGraph: {
      type: 'website',
      siteName: 'Miaurmario',
      url: origin,
      locale: locale === 'en' ? 'en_US' : 'es_ES',
      title,
      description,
      images: [image],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [image.url],
    },
  };
}

export default async function Home() {
  // Read at request time (cached briefly): flipping sign-up to "open" in the admin
  // panel must change the "Crear cuenta" button without a redeploy.
  const signupMode = await fetchSignupMode();

  return (
    <main className="min-h-screen bg-background text-foreground">
      <LandingRedirect />
      <LandingHero mode={signupMode} />
      <LandingFeatures />
      <LandingInstall />
      <LandingTrust mode={signupMode} />
    </main>
  );
}
